language: python
sudo: false
python:
  - "3.4"

install: "pip install -r PersonalWebsite/requirements.txt"
before_script: "touch PersonalWebsite/local_settings.py"
script: "python PersonalWebsite/manage.py test"
